Traceback (most recent call last):
  File "/Users/nehatalluri/Desktop/masters/2/771/final_project/src/train_model.py", line 56, in <module>
    reconstructed = model(batch_data, row_mask)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nehatalluri/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nehatalluri/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nehatalluri/Desktop/masters/2/771/final_project/src/mae.py", line 39, in forward
    row_mask = row_mask.unsqueeze(-1).expand(batch_size, num_rows, num_cols)  # shape: [batch_size, MAX_ROWS, REQUIRED_COLUMNS]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (13) must match the existing size (16) at non-singleton dimension 0.  Target sizes: [13, 1387, 30000].  Tensor sizes: [16, 1387, 1]